---
- name: Installing docker and docker-compose
  hosts: build, web
  become: yes

  tasks:
  - name: Installing latest version docker and docker-compose
    apt:
      pkg:
        - docker
        - docker-compose
      update_cache: yes
      state: present

- name: Building run image
  hosts: build
  become: yes

  tasks:
  - name: Copy build directory to build server
    copy:
      src: ./build
      dest: /

  - name: Compile artifact
    community.docker.docker_compose:
      project_src: /build

  - name: Create run image
    community.docker.docker_compose:
      project_src: /build
      file: /docker-compose-run.yml
      build: yes
      # stopped: yes

  - name: Login into docker hub
    community.docker.docker_login:
      username: artempvl
      password: cfb00c0f-3097-42d7-b18d-984f27200c5e

  - name: Tag and push to docker hub
    community.docker.docker_image:
      name: artempvl/run:latest
      repository: run:latest
      push: yes
      source: local
...