---
- name: Setting up repository
  hosts: repository
  become: yes

  tasks:
  - name: Installing latest version docker and docker-compose
    apt:
      pkg:
        - docker
        - docker-compose
      update_cache: yes
      state: present

- name: Creating repository
  hosts: repository
  become: yes

  tasks:

  - name: Copy docker-compose to host
    copy:
      src: ./repository
      dest: /repository


  - name: Run repository with docker compose of gitlab
    community.docker.docker_compose:
      project_src: /repository
      build: no
...