---
version: "3.6"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: 'hw08-4'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://hw08-4:80'
        gitlab_rails['gitlab_shell_ssh_port'] = 23
    ports:
      - "23:22"
      - "80:80"
      - "443:443"
    volumes:
      - $GITLAB_HOME/data:/var/opt/gitlab
      - $GITLAB_HOME/logs:/var/log/gitlab
      - $GITLAB_HOME/config:/etc/gitlab
...